### ISSUE TITLE
Raspberry Pi instead of beaglebone

### ISSUE THREAD

**Issue by jvegaf** [hzeller/ldgraphy#1]
First of all congrats for the project, it's awesome !!!

Why you use beaglebone ?

It's possible use a raspberry pi ?

Thanks !

**Comment by hzeller** [comment]
Only if you use and program an external fast microcontroller to sent the laser pulses at the right time. Right now, LDGraphy relies on the Programmable Realtime Unit of the BeagleBone to do that.
The BeagleBone Green is $39, the Raspberry Pi $35, so that is $4 well worth spent for reduced complexity.
